version: '3.8'

services:
  selenoid1:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid1
    hostname: selenoid1
    environment:
      - DOCKER_API_VERSION=1.40
    networks:
      - selenoid_net
    ports:
      - "4445:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/browsers.json:/etc/selenoid/browsers.json:ro
    command: -limit 10 -container-network selenoid_net

  selenoid2:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid2
    hostname: selenoid2
    environment:
      - DOCKER_API_VERSION=1.40
    networks:
      - selenoid_net
    ports:
      - "4446:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/browsers.json:/etc/selenoid/browsers.json:ro
    command: -limit 10 -container-network selenoid_net

  ggr:
    image: aerokube/ggr:1.7.2
    container_name: ggr
    hostname: ggr
    depends_on: [selenoid1, selenoid2]
    volumes:
      - ./config/grid-router:/etc/grid-router:ro
    command: -guests-allowed -guests-quota "test" -verbose -quotaDir /etc/grid-router/quota
    networks:
      - selenoid_net
    ports:
      - "4444:4444"

  ggr_ui:
    image: aerokube/ggr-ui:1.2.0
    container_name: ggr_ui
    hostname: ggr_ui
    depends_on: [ ggr ]
    volumes:
      - ./config/grid-router/quota:/etc/grid-router/quota:ro
    networks:
      - selenoid_net
    ports:
      - "8888:8888"
    environment:
      - GGR_URL=http://ggr:4444

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    hostname: selenoid-ui
    depends_on: [ggr_ui]
    networks:
      - selenoid_net
    ports:
      - "8080:8080"
    command: --selenoid-uri http://ggr_ui:8888

  nginx:
    image: nginx:latest
    depends_on: [ggr, selenoid-ui]
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    container_name: nginx
    networks:
      - selenoid_net

networks:
  selenoid_net:
    name: selenoid_net  # Общая сеть для всех
    driver: bridge